/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conexion;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EstudianteUC
 */
public class FrmMascotas extends javax.swing.JFrame {

    /**
     * Creates new form FrmMascotas
     */
    public FrmMascotas() {
         initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
        vaciarTabla();
        verDatos();
    }
public void limpiar() {
        TxtCodigo.setText("");
        TxtNombreMascota.setText("");
        TxtEdad.setText("");
        TxtRaza.setText("");
        TxtEspecie.setText("");
        TxtPeso.setText("");
    }
public void vaciarTabla() {
        DefaultTableModel Modelo = (DefaultTableModel) jTable1.getModel();
        String titulos[] = {"ID", "Nombre", "Edad", "Raza", "Especie", "Peso"};
        Modelo = new DefaultTableModel(null, titulos);
        jTable1.setModel(Modelo);
    }
 public void verDatos() {
       try {
        Connection con1 = new Conectar().getConexion();

        // NUEVO MODELO con cabecera definida desde cero
        String[] titulos = {"ID", "Nombre", "Edad", "Raza", "Especie", "Peso"};
        DefaultTableModel miModelo = new DefaultTableModel(null, titulos);

        String sql = "SELECT * FROM TMascota";
        Statement st = con1.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            String[] fila = new String[6];
            fila[0] = rs.getString("Id");
            fila[1] = rs.getString("nombre_mascota");
            fila[2] = rs.getString("edad");
            fila[3] = rs.getString("raza");
            fila[4] = rs.getString("especie");
            fila[5] = rs.getString("peso");
            miModelo.addRow(fila);
        }

        jTable1.setModel(miModelo);  // Ahora sí lo aplica correctamente

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al visualizar mascotas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNombreMascota = new javax.swing.JTextField();
        TxtEdad = new javax.swing.JTextField();
        TxtCodigo = new javax.swing.JTextField();
        TxtRaza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtEspecie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtPeso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnNuevo = new javax.swing.JButton();
        BtnGrabar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N
        jLabel1.setText("REGISTRO DE MASCOTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Edad :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Raza :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        TxtNombreMascota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtNombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreMascotaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 350, -1));

        TxtEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(TxtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 350, -1));

        TxtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 350, -1));

        TxtRaza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(TxtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 350, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Especie:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        TxtEspecie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(TxtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 350, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Peso:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        TxtPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(TxtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 350, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Edad", "Raza", "Especie", "Peso"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 650, 280));

        BtnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 120, 50));

        BtnGrabar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnGrabar.setText("Grabar");
        BtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 120, 50));

        BtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 120, 50));

        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 120, 50));

        BtnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 650, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreMascotaActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
         limpiar();
        TxtNombreMascota.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed
       if (TxtNombreMascota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falta ingresar el nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
            TxtNombreMascota.requestFocus();
        } else {
            try {
                Connection con = new Conectar().getConexion();
                String sql = "INSERT INTO TMascota(nombre_mascota, edad, raza, especie, peso) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, TxtNombreMascota.getText());
                pst.setInt(2, Integer.parseInt(TxtEdad.getText()));
                pst.setString(3, TxtRaza.getText());
                pst.setString(4, TxtEspecie.getText());
                pst.setDouble(5, Double.parseDouble(TxtPeso.getText()));
                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "Mascota registrada correctamente");
                    limpiar();
                    vaciarTabla();
                    verDatos();
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Error al registrar mascota", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
         try {
            Connection con = new Conectar().getConexion();
            String sql = "UPDATE TMascota SET nombre_mascota=?, edad=?, raza=?, especie=?, peso=? WHERE Id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, TxtNombreMascota.getText());
            pst.setInt(2, Integer.parseInt(TxtEdad.getText()));
            pst.setString(3, TxtRaza.getText());
            pst.setString(4, TxtEspecie.getText());
            pst.setDouble(5, Double.parseDouble(TxtPeso.getText()));
            pst.setInt(6, Integer.parseInt(TxtCodigo.getText()));
            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Mascota actualizada correctamente");
                limpiar();
                vaciarTabla();
                verDatos();
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar mascota", "Error", JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            int opc = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta mascota?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    Connection con = new Conectar().getConexion();
                    String sql = "DELETE FROM TMascota WHERE Id=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setInt(1, Integer.parseInt(TxtCodigo.getText()));
                    int n = pst.executeUpdate();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(this, "Mascota eliminada correctamente");
                        limpiar();
                        vaciarTabla();
                        verDatos();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error al eliminar mascota", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
         JOptionPane.showMessageDialog(null, "Saliendo del formulario...");
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        TxtCodigo.setText(jTable1.getValueAt(fila, 0).toString());
        TxtNombreMascota.setText(jTable1.getValueAt(fila, 1).toString());
        TxtEdad.setText(jTable1.getValueAt(fila, 2).toString());
        TxtRaza.setText(jTable1.getValueAt(fila, 3).toString());
        TxtEspecie.setText(jTable1.getValueAt(fila, 4).toString());
        TxtPeso.setText(jTable1.getValueAt(fila, 5).toString());
    } // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtEspecie;
    private javax.swing.JTextField TxtNombreMascota;
    private javax.swing.JTextField TxtPeso;
    private javax.swing.JTextField TxtRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
