package Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
   private int intentosFallidos = 0;
   private final int MAX_INTENTOS = 3;
    private Conectar conexionBD; // Crear una instancia de la clase Conexion
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        conexionBD = new Conectar(); // Inicializar la conexión
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        BtnInicioSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        TxtPswd = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNivelAcceso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnInicioSesion.setText("Iniciar Sesión");
        BtnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioSesionActionPerformed(evt);
            }
        });
        Bg.add(BtnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 60));

        jLabel3.setBackground(new java.awt.Color(255, 0, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Inicio de Sesión");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 288, 39));

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        Bg.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 119, 55));

        TxtPswd.setText("1234");
        Bg.add(TxtPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 254, -1));

        jLabel2.setText("Clave");
        Bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        TxtUser.setText("Admin");
        Bg.add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 254, -1));

        jLabel1.setText("Usuario");
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N
        jLabel5.setText("Agrovelas");

        jLabel6.setText("<html>Este es un texto largo que se ajustará automáticamente en varias líneas</html>");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setToolTipText("");

        jLabel6.setText("<html>Este es un texto largo que se ajustará automáticamente en varias líneas</html>");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setToolTipText("");

        jLabel6.setText("<html>Este es un texto largo que se ajustará automáticamente en varias líneas</html>");
        jLabel8.setToolTipText("");

        jLabel6.setText("<html>Este es un texto largo que se ajustará automáticamente en varias líneas</html>");
        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setToolTipText("");

        jLabel6.setText("<html>Este es un texto largo que se ajustará automáticamente en varias líneas</html>");
        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setToolTipText("");

        jLabel6.setText("<html>Este es un texto largo que se ajustará automáticamente en varias líneas</html>");
        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        Bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 400));

        jLabel4.setText("Nivel  de acceso:");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 100, -1));
        Bg.add(TxtNivelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioSesionActionPerformed
        String usuario = this.TxtUser.getText();  
    String contrasena = new String(this.TxtPswd.getPassword());  
    iniciarSesion(usuario, contrasena);  // Inicia sesión con los datos ingresados
    }//GEN-LAST:event_BtnInicioSesionActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed
// Método para realizar la validación de inicio de sesión
    
    // Método para realizar la validación de inicio de sesión
    private void iniciarSesion(String usuario, String contrasena) {
        Connection conexion = conexionBD.getConexion();
    
    // Consulta para obtener también el nivel de acceso
    String consultaSQL = "SELECT nivel_acceso FROM TUsuarios WHERE usuario = ? AND clave = ?";

    try (PreparedStatement sentencia = conexion.prepareStatement(consultaSQL)) {
        sentencia.setString(1, usuario);
        sentencia.setString(2, contrasena);

        ResultSet resultado = sentencia.executeQuery();

        if (resultado.next()) {
            // Obtenemos el nivel de acceso
            String nivelAcceso = resultado.getString("nivel_acceso");

            // Mostramos el nivel en el campo correspondiente
            TxtNivelAcceso.setText(nivelAcceso);

            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso. Nivel: " + nivelAcceso);

            // Abrir menú principal
            FrmMenu menu = new FrmMenu();
            menu.setVisible(true);
            menu.setExtendedState(FrmMenu.MAXIMIZED_BOTH);
            this.dispose();  // Cierra formulario de inicio de sesión

        } else {
            // Manejo de intentos fallidos
            intentosFallidos++;
            int intentosRestantes = MAX_INTENTOS - intentosFallidos;

            if (intentosRestantes > 0) {
                JOptionPane.showMessageDialog(this,
                    "Usuario o contraseña incorrectos.\nIntentos restantes: " + intentosRestantes);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Superaste el número máximo de intentos. Comuníquese con soporte.");
                System.exit(0);
            }
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error en la conexión a la base de datos.");
    } finally {
        conexionBD.cerrarConexion();
    }
    }

    public static void main(String args[]) {
        // Crear y mostrar el formulario
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnInicioSesion;
    private javax.swing.JTextField TxtNivelAcceso;
    private javax.swing.JPasswordField TxtPswd;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
